--- 
title: "Bioinformatika"
author: "Lucie Pfeiferová"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: pfeiferl/handbook_bioinfoCZ
description: "Příručka pro magisterské studenty pokrývající základní problematiku (genomické) bioinformatiky"
---
# Prerequisites {-}

Skripta Bioinformatika: Základy vznikla z potřeby moderního výukového materiálu pro studijní obor Bioinformatika. Kapitoly pokrývají nejdůležitější témata, se kterými se student (genomické) bioinformatiky může setkat. V první části je obecně popsána bioinformatika, základy biologie a sekvenační techniky, databáze a nástroje. Následující kapitoly popisují zpracování a kontrolu kvality hrubých sekvenačních dat, alignment, mapování a assembly. Poslední kapitoly popisují následné zpracování získaných dat, včetně funkční analýzy. Skripta jsou zaměřena především pro studenty předmětů Genomika: Algoritmy a analýza a Analýza genové exprese. Užitečné informace v ní však najdou i další zájemci o tento obor.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
